### ISSUE TITLE
Get script.py running locally with gcloud.

### ISSUE THREAD

**Issue by twesterhout** [mlp2018/fraud_detection#2]
[script.py](https://github.com/mlp2018/fraud_detection/blob/master/script.py) is a kernel taken from [Kaggle](https://www.kaggle.com/aloisiodn/lgbm-starter-early-stopping-0-9539) that we've agreed to use as a starting point. The idea is now for everyone to download [Google Cloud SDK](https://cloud.google.com/sdk/docs/quickstarts) and try to get `script.py` running under `gcloud` locally.

**Comment by aranas** [comment]
So, is it correct, that we need to switch to python 2.7 in order to use Google Cloud?

**Comment by twesterhout** [comment]
AFAIK yes.
