### ISSUE TITLE
Nastaran's assignment: understand the dataset

### ISSUE THREAD

**Issue by johannadevos** [mlp2018/fraud_detection#27]
This issue is an assignment from Nastaran. She wants us to thoroughly understand the nature of the data, and would like for everyone to read the [kernel](https://www.kaggle.com/gopisaran/indepth-eda-entire-talkingdata-dataset) that does data visualisation.

**Comment by andregalvez79** [comment]
[here](https://www.kaggle.com/kailex/talkingdata-eda-and-class-imbalance) are also some nice plots.
