### ISSUE TITLE
Nastaran's assignment: investigate features further

### ISSUE THREAD

**Issue by johannadevos** [mlp2018/fraud_detection#28]
Nastaran would like for us to investigate which features are the most informative, and also what are the relations between the different features.

**Comment by aranas** [comment]
most informative based on what? Our intuition or our current implementation of lgbm? Did she specify?

**Comment by johannadevos** [comment]
She did not specify. But I remember reading a [blog](http://andybromberg.com/sentiment-analysis-python/) a while ago that also did an analysis about the informativeness of features. It's not directly transferable to our case because this blog is about sentiment analysis (scroll down to about 1/4th for the feature analysis), but I guess in our case it would be something like: those users who downloaded an app were 3 times more likely to have a Windows os rather than a Mac os (for example). And then the most informative feature is the one with the highest factor (as in, X times more likely). Does this make sense?
