### ISSUE TITLE
fix preprocess_confidence

### ISSUE THREAD

**Issue by aranas** [mlp2018/fraud_detection#37]
At the moment preprocess_confidence is called three times in the main script and each time it recomputes the new features only that sometimes it will merge with valid and sometimes with test data or none of them. This can surely be improved by simply outputing the features and doing the merge in an extra function. If someone has time on their hands, please feel free to fix it.

**Comment by johannadevos** [comment]
I pushed the code. I'm not 100% sure if it is maximally efficient now, but at least the merge is no longer performed three times for the training data. Groupby is still performed for the training data each time, and I've been wondering whether that can be done more efficiently, but this is where it's currently at.
