### ISSUE TITLE
Running our script in the cloud: read and write files with Tensorflow

### ISSUE THREAD

**Issue by johannadevos** [mlp2018/fraud_detection#39]
I'm trying to run `lightgbm_main.py` in the cloud, but Google Cloud cannot read the files when it is specified they should be opened with `pandas.read_csv()`. Instead, the files should be read with Tensorflow's [FileIO class](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/io/file_io.py). 

I've started to implement this, but I cannot find much documentation and have trouble converting the Pandas read method to the Tensorflow one. Specifically, it concerns the `load_train_raw()` and `load_test_raw()` functions in `preprocessing.py`. They currently look like this:

`def load_train_raw(filename):
    columns = ['ip','app','device','os', 'channel', 'click_time',
               'is_attributed']
    logging.info('Loading labeled data from {!r}...'.format(filename))
    return pd.read_csv(filename, dtype=DTYPES, usecols=columns)`

They should become something like:

`def load_train_raw(filename):
    columns = ['ip','app','device','os', 'channel', 'click_time',
               'is_attributed']
    logging.info('Loading labeled data from {!r}...'.format(filename))
    loaded_data = file_io.FileIO(filename, mode = 'rb')
    return loaded_data`

However, the second chunk of code does not use `dtype` or `usecols` in any way, and I believe this is the cause of the `AttributeError` I get in the cloud: "'FileIO' object has no attribute 'click_time'".

Could someone help me to solve this bug? It's probably relatively easy but I just don't see it at this point.

The code is in the `gcloud` branch. The script can be run from the command line as follows:

`gcloud ml-engine jobs submit training gbm_90_10_16 --stream-logs --runtime-version 1.6 --staging-bucket gs://bag_of_students --module-name trainer.lightgbm_main --package-path ./trainer --config ./trainer/config.yaml --region us-east1 --project mlip-team-bagofstudents -- --train-file gs://bag_of_students/data/train_small_90.csv --valid-file gs://bag_of_students/data/train_small_10.csv --test-file gs://bag_of_students/data/test.csv --job-dir gs://bag_of_students/results --run submission`

Some potentially useful links:
https://stackoverflow.com/questions/48569618/how-do-i-use-pandas-read-csv-on-google-cloud-ml
https://stackoverflow.com/questions/42799117/google-cloud-ml-and-gcs-bucket-issues/42799952#42799952
https://stackoverflow.com/questions/42761075/reading-files-in-google-cloud-machine-learning
https://stackoverflow.com/questions/41633748/load-numpy-array-in-google-cloud-ml-job

**Comment by twesterhout** [comment]
Fixed in master.
